extern __varcall __asm_import("equinoxe-animate") void animate_init();
extern __varcall __asm_import("equinoxe-animate") __zp_reserve( 55,56,57,46,49,52 ) __zp($31) char animate_add(__zp($31) char count, __zp($39) char state, __zp($38) char loop, __zp($2e) char speed, __zp($34) signed char direction, __zp($37) char reverse);
extern __varcall __asm_import("equinoxe-animate") __zp_reserve( 46 ) void animate_logic(__zp($2e) char a);
extern __varcall __asm_import("equinoxe-animate") __zp_reserve( 46,49 ) __zp($2e) char animate_is_waiting(__zp($31) char a);
extern __varcall __asm_import("equinoxe-animate") __zp_reserve( 56,46 ) __zp($2e) char animate_get_image(__zp($38) char a);
extern __varcall __asm_import("equinoxe-animate") __zp_reserve( 57,46 ) __zp($2e) char animate_get_transition(__zp($39) char a);
extern __varcall __asm_import("equinoxe-animate") __zp_reserve( 46,49 ) __zp($2e) char animate_del(__zp($31) char a);
extern __varcall __asm_import("equinoxe-animate") __zp_reserve( 58,59,52,53,54 ) void animate_player(__zp($34) char a, __zp($35) int x, __zp($3a) int px);
extern __varcall __asm_import("equinoxe-animate") __zp_reserve( 55,47,48,53,54 ) void animate_tower(__zp($37) char a);
extern __varcall __asm_import("equinoxe-animate") __zp_reserve( 44,34,45,35,49,40,41 ) void animate_debug(__zp($31) char a);
extern __phicall __asm_import("equinoxe-animate") void __equinoxe_animate_start();
