extern __varcall __lib_import("equinoxe-layers") void vera_petscii_init();
extern __varcall __lib_import("equinoxe-layers") void vera_floor_layer0();
extern __varcall __lib_import("equinoxe-layers") void vera_floor_layer1();
extern __varcall __lib_import("equinoxe-layers") void vera_petscii_layer1();
extern __varcall __lib_import("equinoxe-layers") void vera_floor_layer0_show();
extern __varcall __lib_import("equinoxe-layers") void vera_floor_layer1_show();
extern __varcall __lib_import("equinoxe-layers") void vera_floor_layer0_hide();
extern __varcall __lib_import("equinoxe-layers") void vera_floor_layer1_hide();
extern __phicall __lib_import("equinoxe-layers") void __equinoxe_layers_start();
