extern __stackcall __lib_import("lib_conio") void clrscr();
extern __stackcall __lib_import("lib_conio") void gotoxy(__register(Y) char x, __register(X) char y);
extern __stackcall __lib_import("lib_conio") __register(A) char wherex();
extern __stackcall __lib_import("lib_conio") __register(A) char wherey();
extern __stackcall __lib_import("lib_conio") void screensize(__zp char *x, __zp char *y);
extern __stackcall __lib_import("lib_conio") __register(A) char screensizex();
extern __stackcall __lib_import("lib_conio") __register(A) char screensizey();
extern __stackcall __lib_import("lib_conio") void cputln();
extern __stackcall __lib_import("lib_conio") void cputcxy(__register(Y) char x, __mem() char y, __mem() char c);
extern __stackcall __lib_import("lib_conio") void cputs(__zp const char *s);
extern __stackcall __lib_import("lib_conio") void cputsxy(__register(Y) char x, __mem() char y, __zp const char *s);
extern __stackcall __lib_import("lib_conio") __register(A) char textcolor(__mem() char color);
extern __stackcall __lib_import("lib_conio") __register(A) char bgcolor(__register(X) char color);
extern __stackcall __lib_import("lib_conio") __register(A) char bordercolor(__register(A) char color);
extern __stackcall __lib_import("lib_conio") __register(A) char kbhit();
extern __stackcall __lib_import("lib_conio") __register(A) char cursor(__register(X) char onoff);
extern __stackcall __lib_import("lib_conio") __register(X) char scroll(__register(A) char onoff);
extern __stackcall __lib_import("lib_conio") void screenlayer1();
extern __stackcall __lib_import("lib_conio") __register(A) char cpeekc();
extern __stackcall __lib_import("lib_conio") __register(A) char cpeekcxy(__register(Y) char x, __register(X) char y);
extern __stackcall __lib_import("lib_conio") void printf_str(__zp void (*putc)(char), __zp const char *s);
extern __stackcall __lib_import("lib_conio") void printf_uint(__zp void (*putc)(char), __mem() unsigned int uvalue, __mem() char format_min_length, __mem() char format_justify_left, __register(Y) char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __register(X) char format_radix);
extern __stackcall __lib_import("lib_conio") void printf_sint(__zp void (*putc)(char), __mem() int value, __mem() char format_min_length, __mem() char format_justify_left, __register(Y) char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __register(X) char format_radix);
extern __stackcall __lib_import("lib_conio") void printf_ulong(__zp void (*putc)(char), __mem() unsigned long uvalue, __mem() char format_min_length, __mem() char format_justify_left, __register(Y) char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __register(X) char format_radix);
extern __stackcall __lib_import("lib_conio") void printf_slong(__zp void (*putc)(char), __mem() long value, __mem() char format_min_length, __mem() char format_justify_left, __register(Y) char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __register(X) char format_radix);
extern __stackcall __lib_import("lib_conio") void printf_uchar(__zp void (*putc)(char), __mem() char uvalue, __mem() char format_min_length, __mem() char format_justify_left, __register(Y) char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __register(A) char format_radix);
extern __stackcall __lib_import("lib_conio") void printf_schar(__zp void (*putc)(char), __register(Y) signed char value, __mem() char format_min_length, __mem() char format_justify_left, __mem() char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __mem() char format_radix);
extern __stackcall __lib_import("lib_conio") void cputc(__register(X) char c);
extern __phicall __lib_import("lib_conio") void conio_x16_init();
extern __phicall __lib_import("lib_conio") void __lib_conio_start();
