.segmentdef Code 
.segmentdef CodeBramHeap 
.segmentdef CodeVeraHeap 
.segmentdef CodeLruCache 
.segmentdef CodeEngineFlight 
.segmentdef CodeEngineFloor 
.segmentdef CodeEngineAnimate 
.segmentdef CodeEnginePalette 

.segmentdef Data
.segmentdef DataBramHeap 
.segmentdef DataVeraHeap 
.segmentdef DataEngineAnimate 
.segmentdef DataEnginePalette 
.segmentdef DataEngineFloor 
.segmentdef DataEngineStages
.segmentdef DataEngineBullets
.segmentdef DataEnginePlayers
.segmentdef DataEngineEnemies
.segmentdef DataEngineTowers
.segmentdef DataEngineFlight 
.segmentdef DataSpriteCache


//.segmentdef BramEngineFloor 


.segmentdef Hash                    [start=$0400, min=$0400, max=$06FF, align=$100]

.segmentdef Debug                   [startAfter="Hash", align=$100]

.segmentdef BramBramHeap            [start=$A000, min=$A000, max=$BFFF, align=$100]
.segmentdef BramVeraHeap            [start=$A000, min=$A000, max=$BFFF, align=$100]

//.segmentdef CodeVeraHeap            [startAfter="BramVeraHeap", min=$A000, max=$BFFF, align=$100] 
//.segmentdef DataVeraHeap            [startAfter="CodeVeraHeap", min=$A000, max=$BFFF, align=$100] 

.segmentdef CodeEngineStages        [start=$A000, min=$A000, max=$BFFF, align=$100]
.segmentdef BramEngineStages        [startAfter="CodeEngineStages", min=$A000, max=$BFFF, align=$100]
.segmentdef CodeEnginePlayers       [start=$A000, min=$A000, max=$BFFF, align=$100]
.segmentdef CodeEngineBullets       [start=$A000, min=$A000, max=$BFFF, align=$100]
.segmentdef CodeEngineEnemies       [start=$A000, min=$A000, max=$BFFF, align=$100]
.segmentdef CodeEngineTowers        [start=$A000, min=$A000, max=$BFFF, align=$100]

.segmentdef BramEngineFloor         [start=$A000, min=$A000, align=$100]
.segmentdef BramEngineFlight        [start=$A000, min=$A000, max=$BF00, align=$100]
.segmentdef BramEnginePalette       [start=$A000, min=$A000, max=$BFFF, align=$100]

//.segmentdef CodeEngineFloor         [start=$A000, min=$A000, max=$BF00, align=$100]
//.segmentdef CodeEngineFlight        [start=$A000, min=$A000, max=$BFFF, align=$100]
