struct cx16_conio_s;
struct printf_buffer_number;
extern __asm_import("lib_conio") __mem() struct cx16_conio_s __conio;
extern __asm_import("lib_conio") __mem() struct printf_buffer_number printf_buffer;
extern __varcall __asm_import("lib_conio") void clrscr();
extern __varcall __asm_import("lib_conio") void gotoxy(__mem() char x, __mem() char y);
extern __varcall __asm_import("lib_conio") __mem() char wherex();
extern __varcall __asm_import("lib_conio") __mem() char wherey();
extern __varcall __asm_import("lib_conio") __zp_reserve( 44,45,40,41 ) void screensize(__zp($28) char *x, __zp($2c) char *y);
extern __varcall __asm_import("lib_conio") __mem() char screensizex();
extern __varcall __asm_import("lib_conio") __mem() char screensizey();
extern __varcall __asm_import("lib_conio") void cputln();
extern __varcall __asm_import("lib_conio") void cputcxy(__mem() char x, __mem() char y, __mem() char c);
extern __varcall __asm_import("lib_conio") __zp_reserve( 42,43 ) void cputs(__zp($2a) const char *s);
extern __varcall __asm_import("lib_conio") __zp_reserve( 40,41,42,43 ) void cputsxy(__mem() char x, __mem() char y, __zp($28) const char *s);
extern __varcall __asm_import("lib_conio") __mem() char textcolor(__mem() char color);
extern __varcall __asm_import("lib_conio") __mem() char bgcolor(__mem() char color);
extern __varcall __asm_import("lib_conio") __mem() char bordercolor(__mem() char color);
extern __varcall __asm_import("lib_conio") __mem() char kbhit();
extern __varcall __asm_import("lib_conio") __mem() char cursor(__mem() char onoff);
extern __varcall __asm_import("lib_conio") __mem() char scroll(__mem() char onoff);
extern __varcall __asm_import("lib_conio") void screenlayer1();
extern __varcall __asm_import("lib_conio") __mem() char cpeekc();
extern __varcall __asm_import("lib_conio") __mem() char cpeekcxy(__mem() char x, __mem() char y);
extern __varcall __asm_import("lib_conio") __zp_reserve( 34,35,40,41 ) void printf_str(__zp($28) void (*putc)(char), __zp($22) const char *s);
extern __varcall __asm_import("lib_conio") __zp_reserve( 44,34,45,35,36,37,38,39,40,41,42,43 ) void printf_uint(__zp($2c) void (*putc)(char), __mem() unsigned int uvalue, __mem() char format_min_length, __mem() char format_justify_left, __mem() char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __mem() char format_radix);
extern __varcall __asm_import("lib_conio") __zp_reserve( 34,35,36,37,38,39,40,41,42,43 ) void printf_sint(__zp($2a) void (*putc)(char), __mem() int value, __mem() char format_min_length, __mem() char format_justify_left, __mem() char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __mem() char format_radix);
extern __varcall __asm_import("lib_conio") __zp_reserve( 44,34,45,35,36,37,38,39,40,41,42,43 ) void printf_ulong(__zp($2c) void (*putc)(char), __mem() unsigned long uvalue, __mem() char format_min_length, __mem() char format_justify_left, __mem() char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __mem() char format_radix);
extern __varcall __asm_import("lib_conio") __zp_reserve( 34,35,36,37,38,39,40,41,42,43 ) void printf_slong(__zp($2a) void (*putc)(char), __mem() long value, __mem() char format_min_length, __mem() char format_justify_left, __mem() char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __mem() char format_radix);
extern __varcall __asm_import("lib_conio") __zp_reserve( 44,34,45,35,36,37,38,39,40,41,42,43 ) void printf_uchar(__zp($2c) void (*putc)(char), __mem() char uvalue, __mem() char format_min_length, __mem() char format_justify_left, __mem() char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __mem() char format_radix);
extern __varcall __asm_import("lib_conio") __zp_reserve( 34,35,36,37,38,39,40,41,42,43 ) void printf_schar(__zp($2a) void (*putc)(char), __mem() signed char value, __mem() char format_min_length, __mem() char format_justify_left, __mem() char format_sign_always, __mem() char format_zero_padding, __mem() char format_upper_case, __mem() char format_radix);
extern __stackcall __asm_import("lib_conio") void cputc(__register(X) char c);
extern __phicall __asm_import("lib_conio") void conio_x16_init();
extern __phicall __asm_import("lib_conio") void __lib_conio_start();
